import fs from 'fs';
import path from 'path';
import HtmlWebpackPlugin from 'html-webpack-plugin';

function templateContent() {
  return fs.readFileSync(
    path.resolve(process.cwd(), 'src/index.html'),
  ).toString();
}

function indexHtml() {
  return {
    plugins: [
      new HtmlWebpackPlugin({
        inject: true, // Inject all files generated by webpack,
        templateContent: templateContent(),
        minify: {
          removeComments: true,
          collapseWhitespace: true,
          removeRedundantAttributes: true,
          useShortDoctype: true,
          removeEmptyAttributes: true,
          removeStyleLinkTypeAttributes: true,
          keepClosingSlash: true,
          minifyJS: true,
          minifyCSS: true,
          minifyURLs: true
        },
      }),
    ],
  };
}

export default indexHtml;
